// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: my_grpc.proto
// Protobuf C++ Version: 5.29.0

#include "my_grpc.pb.h"

#include <algorithm>
#include <type_traits>
#include "google/protobuf/io/coded_stream.h"
#include "google/protobuf/generated_message_tctable_impl.h"
#include "google/protobuf/extension_set.h"
#include "google/protobuf/generated_message_util.h"
#include "google/protobuf/wire_format_lite.h"
#include "google/protobuf/descriptor.h"
#include "google/protobuf/generated_message_reflection.h"
#include "google/protobuf/reflection_ops.h"
#include "google/protobuf/wire_format.h"
// @@protoc_insertion_point(includes)

// Must be included last.
#include "google/protobuf/port_def.inc"
PROTOBUF_PRAGMA_INIT_SEG
namespace _pb = ::google::protobuf;
namespace _pbi = ::google::protobuf::internal;
namespace _fl = ::google::protobuf::internal::field_layout;
namespace my_grpc {

inline constexpr UserLoginResponse::Impl_::Impl_(
    ::_pbi::ConstantInitialized) noexcept
      : uid_(
            &::google::protobuf::internal::fixed_address_empty_string,
            ::_pbi::ConstantInitialized()),
        token_(
            &::google::protobuf::internal::fixed_address_empty_string,
            ::_pbi::ConstantInitialized()),
        error_{0},
        _cached_size_{0} {}

template <typename>
PROTOBUF_CONSTEXPR UserLoginResponse::UserLoginResponse(::_pbi::ConstantInitialized)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(_class_data_.base()),
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(),
#endif  // PROTOBUF_CUSTOM_VTABLE
      _impl_(::_pbi::ConstantInitialized()) {
}
struct UserLoginResponseDefaultTypeInternal {
  PROTOBUF_CONSTEXPR UserLoginResponseDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~UserLoginResponseDefaultTypeInternal() {}
  union {
    UserLoginResponse _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 UserLoginResponseDefaultTypeInternal _UserLoginResponse_default_instance_;

inline constexpr UserLoginRequest::Impl_::Impl_(
    ::_pbi::ConstantInitialized) noexcept
      : uid_(
            &::google::protobuf::internal::fixed_address_empty_string,
            ::_pbi::ConstantInitialized()),
        token_(
            &::google::protobuf::internal::fixed_address_empty_string,
            ::_pbi::ConstantInitialized()),
        _cached_size_{0} {}

template <typename>
PROTOBUF_CONSTEXPR UserLoginRequest::UserLoginRequest(::_pbi::ConstantInitialized)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(_class_data_.base()),
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(),
#endif  // PROTOBUF_CUSTOM_VTABLE
      _impl_(::_pbi::ConstantInitialized()) {
}
struct UserLoginRequestDefaultTypeInternal {
  PROTOBUF_CONSTEXPR UserLoginRequestDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~UserLoginRequestDefaultTypeInternal() {}
  union {
    UserLoginRequest _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 UserLoginRequestDefaultTypeInternal _UserLoginRequest_default_instance_;

inline constexpr GetVerifyResponse::Impl_::Impl_(
    ::_pbi::ConstantInitialized) noexcept
      : phone_(
            &::google::protobuf::internal::fixed_address_empty_string,
            ::_pbi::ConstantInitialized()),
        code_(
            &::google::protobuf::internal::fixed_address_empty_string,
            ::_pbi::ConstantInitialized()),
        error_{0},
        _cached_size_{0} {}

template <typename>
PROTOBUF_CONSTEXPR GetVerifyResponse::GetVerifyResponse(::_pbi::ConstantInitialized)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(_class_data_.base()),
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(),
#endif  // PROTOBUF_CUSTOM_VTABLE
      _impl_(::_pbi::ConstantInitialized()) {
}
struct GetVerifyResponseDefaultTypeInternal {
  PROTOBUF_CONSTEXPR GetVerifyResponseDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~GetVerifyResponseDefaultTypeInternal() {}
  union {
    GetVerifyResponse _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 GetVerifyResponseDefaultTypeInternal _GetVerifyResponse_default_instance_;

inline constexpr GetVerifyRequest::Impl_::Impl_(
    ::_pbi::ConstantInitialized) noexcept
      : phone_(
            &::google::protobuf::internal::fixed_address_empty_string,
            ::_pbi::ConstantInitialized()),
        _cached_size_{0} {}

template <typename>
PROTOBUF_CONSTEXPR GetVerifyRequest::GetVerifyRequest(::_pbi::ConstantInitialized)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(_class_data_.base()),
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(),
#endif  // PROTOBUF_CUSTOM_VTABLE
      _impl_(::_pbi::ConstantInitialized()) {
}
struct GetVerifyRequestDefaultTypeInternal {
  PROTOBUF_CONSTEXPR GetVerifyRequestDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~GetVerifyRequestDefaultTypeInternal() {}
  union {
    GetVerifyRequest _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 GetVerifyRequestDefaultTypeInternal _GetVerifyRequest_default_instance_;

inline constexpr GetChatServerResponse::Impl_::Impl_(
    ::_pbi::ConstantInitialized) noexcept
      : host_(
            &::google::protobuf::internal::fixed_address_empty_string,
            ::_pbi::ConstantInitialized()),
        token_(
            &::google::protobuf::internal::fixed_address_empty_string,
            ::_pbi::ConstantInitialized()),
        error_{0},
        port_{0},
        _cached_size_{0} {}

template <typename>
PROTOBUF_CONSTEXPR GetChatServerResponse::GetChatServerResponse(::_pbi::ConstantInitialized)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(_class_data_.base()),
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(),
#endif  // PROTOBUF_CUSTOM_VTABLE
      _impl_(::_pbi::ConstantInitialized()) {
}
struct GetChatServerResponseDefaultTypeInternal {
  PROTOBUF_CONSTEXPR GetChatServerResponseDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~GetChatServerResponseDefaultTypeInternal() {}
  union {
    GetChatServerResponse _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 GetChatServerResponseDefaultTypeInternal _GetChatServerResponse_default_instance_;

inline constexpr GetChatServerRequest::Impl_::Impl_(
    ::_pbi::ConstantInitialized) noexcept
      : uid_(
            &::google::protobuf::internal::fixed_address_empty_string,
            ::_pbi::ConstantInitialized()),
        _cached_size_{0} {}

template <typename>
PROTOBUF_CONSTEXPR GetChatServerRequest::GetChatServerRequest(::_pbi::ConstantInitialized)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(_class_data_.base()),
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(),
#endif  // PROTOBUF_CUSTOM_VTABLE
      _impl_(::_pbi::ConstantInitialized()) {
}
struct GetChatServerRequestDefaultTypeInternal {
  PROTOBUF_CONSTEXPR GetChatServerRequestDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~GetChatServerRequestDefaultTypeInternal() {}
  union {
    GetChatServerRequest _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 GetChatServerRequestDefaultTypeInternal _GetChatServerRequest_default_instance_;
}  // namespace my_grpc
static constexpr const ::_pb::EnumDescriptor**
    file_level_enum_descriptors_my_5fgrpc_2eproto = nullptr;
static constexpr const ::_pb::ServiceDescriptor**
    file_level_service_descriptors_my_5fgrpc_2eproto = nullptr;
const ::uint32_t
    TableStruct_my_5fgrpc_2eproto::offsets[] ABSL_ATTRIBUTE_SECTION_VARIABLE(
        protodesc_cold) = {
        ~0u,  // no _has_bits_
        PROTOBUF_FIELD_OFFSET(::my_grpc::GetVerifyRequest, _internal_metadata_),
        ~0u,  // no _extensions_
        ~0u,  // no _oneof_case_
        ~0u,  // no _weak_field_map_
        ~0u,  // no _inlined_string_donated_
        ~0u,  // no _split_
        ~0u,  // no sizeof(Split)
        PROTOBUF_FIELD_OFFSET(::my_grpc::GetVerifyRequest, _impl_.phone_),
        ~0u,  // no _has_bits_
        PROTOBUF_FIELD_OFFSET(::my_grpc::GetVerifyResponse, _internal_metadata_),
        ~0u,  // no _extensions_
        ~0u,  // no _oneof_case_
        ~0u,  // no _weak_field_map_
        ~0u,  // no _inlined_string_donated_
        ~0u,  // no _split_
        ~0u,  // no sizeof(Split)
        PROTOBUF_FIELD_OFFSET(::my_grpc::GetVerifyResponse, _impl_.error_),
        PROTOBUF_FIELD_OFFSET(::my_grpc::GetVerifyResponse, _impl_.phone_),
        PROTOBUF_FIELD_OFFSET(::my_grpc::GetVerifyResponse, _impl_.code_),
        ~0u,  // no _has_bits_
        PROTOBUF_FIELD_OFFSET(::my_grpc::GetChatServerRequest, _internal_metadata_),
        ~0u,  // no _extensions_
        ~0u,  // no _oneof_case_
        ~0u,  // no _weak_field_map_
        ~0u,  // no _inlined_string_donated_
        ~0u,  // no _split_
        ~0u,  // no sizeof(Split)
        PROTOBUF_FIELD_OFFSET(::my_grpc::GetChatServerRequest, _impl_.uid_),
        ~0u,  // no _has_bits_
        PROTOBUF_FIELD_OFFSET(::my_grpc::GetChatServerResponse, _internal_metadata_),
        ~0u,  // no _extensions_
        ~0u,  // no _oneof_case_
        ~0u,  // no _weak_field_map_
        ~0u,  // no _inlined_string_donated_
        ~0u,  // no _split_
        ~0u,  // no sizeof(Split)
        PROTOBUF_FIELD_OFFSET(::my_grpc::GetChatServerResponse, _impl_.error_),
        PROTOBUF_FIELD_OFFSET(::my_grpc::GetChatServerResponse, _impl_.host_),
        PROTOBUF_FIELD_OFFSET(::my_grpc::GetChatServerResponse, _impl_.port_),
        PROTOBUF_FIELD_OFFSET(::my_grpc::GetChatServerResponse, _impl_.token_),
        ~0u,  // no _has_bits_
        PROTOBUF_FIELD_OFFSET(::my_grpc::UserLoginRequest, _internal_metadata_),
        ~0u,  // no _extensions_
        ~0u,  // no _oneof_case_
        ~0u,  // no _weak_field_map_
        ~0u,  // no _inlined_string_donated_
        ~0u,  // no _split_
        ~0u,  // no sizeof(Split)
        PROTOBUF_FIELD_OFFSET(::my_grpc::UserLoginRequest, _impl_.uid_),
        PROTOBUF_FIELD_OFFSET(::my_grpc::UserLoginRequest, _impl_.token_),
        ~0u,  // no _has_bits_
        PROTOBUF_FIELD_OFFSET(::my_grpc::UserLoginResponse, _internal_metadata_),
        ~0u,  // no _extensions_
        ~0u,  // no _oneof_case_
        ~0u,  // no _weak_field_map_
        ~0u,  // no _inlined_string_donated_
        ~0u,  // no _split_
        ~0u,  // no sizeof(Split)
        PROTOBUF_FIELD_OFFSET(::my_grpc::UserLoginResponse, _impl_.error_),
        PROTOBUF_FIELD_OFFSET(::my_grpc::UserLoginResponse, _impl_.uid_),
        PROTOBUF_FIELD_OFFSET(::my_grpc::UserLoginResponse, _impl_.token_),
};

static const ::_pbi::MigrationSchema
    schemas[] ABSL_ATTRIBUTE_SECTION_VARIABLE(protodesc_cold) = {
        {0, -1, -1, sizeof(::my_grpc::GetVerifyRequest)},
        {9, -1, -1, sizeof(::my_grpc::GetVerifyResponse)},
        {20, -1, -1, sizeof(::my_grpc::GetChatServerRequest)},
        {29, -1, -1, sizeof(::my_grpc::GetChatServerResponse)},
        {41, -1, -1, sizeof(::my_grpc::UserLoginRequest)},
        {51, -1, -1, sizeof(::my_grpc::UserLoginResponse)},
};
static const ::_pb::Message* const file_default_instances[] = {
    &::my_grpc::_GetVerifyRequest_default_instance_._instance,
    &::my_grpc::_GetVerifyResponse_default_instance_._instance,
    &::my_grpc::_GetChatServerRequest_default_instance_._instance,
    &::my_grpc::_GetChatServerResponse_default_instance_._instance,
    &::my_grpc::_UserLoginRequest_default_instance_._instance,
    &::my_grpc::_UserLoginResponse_default_instance_._instance,
};
const char descriptor_table_protodef_my_5fgrpc_2eproto[] ABSL_ATTRIBUTE_SECTION_VARIABLE(
    protodesc_cold) = {
    "\n\rmy_grpc.proto\022\007my_grpc\"!\n\020GetVerifyReq"
    "uest\022\r\n\005phone\030\001 \001(\t\"\?\n\021GetVerifyResponse"
    "\022\r\n\005error\030\001 \001(\005\022\r\n\005phone\030\002 \001(\t\022\014\n\004code\030\003"
    " \001(\t\"#\n\024GetChatServerRequest\022\013\n\003uid\030\001 \001("
    "\t\"Q\n\025GetChatServerResponse\022\r\n\005error\030\001 \001("
    "\005\022\014\n\004host\030\002 \001(\t\022\014\n\004port\030\003 \001(\005\022\r\n\005token\030\004"
    " \001(\t\".\n\020UserLoginRequest\022\013\n\003uid\030\001 \001(\t\022\r\n"
    "\005token\030\002 \001(\t\">\n\021UserLoginResponse\022\r\n\005err"
    "or\030\001 \001(\005\022\013\n\003uid\030\002 \001(\t\022\r\n\005token\030\003 \001(\t2T\n\006"
    "Verify\022J\n\017get_verify_code\022\031.my_grpc.GetV"
    "erifyRequest\032\032.my_grpc.GetVerifyResponse"
    "\"\0002\243\001\n\006Status\022R\n\017get_chat_server\022\035.my_gr"
    "pc.GetChatServerRequest\032\036.my_grpc.GetCha"
    "tServerResponse\"\000\022E\n\nuser_login\022\031.my_grp"
    "c.UserLoginRequest\032\032.my_grpc.UserLoginRe"
    "sponse\"\000b\006proto3"
};
static ::absl::once_flag descriptor_table_my_5fgrpc_2eproto_once;
PROTOBUF_CONSTINIT const ::_pbi::DescriptorTable descriptor_table_my_5fgrpc_2eproto = {
    false,
    false,
    616,
    descriptor_table_protodef_my_5fgrpc_2eproto,
    "my_grpc.proto",
    &descriptor_table_my_5fgrpc_2eproto_once,
    nullptr,
    0,
    6,
    schemas,
    file_default_instances,
    TableStruct_my_5fgrpc_2eproto::offsets,
    file_level_enum_descriptors_my_5fgrpc_2eproto,
    file_level_service_descriptors_my_5fgrpc_2eproto,
};
namespace my_grpc {
// ===================================================================

class GetVerifyRequest::_Internal {
 public:
};

GetVerifyRequest::GetVerifyRequest(::google::protobuf::Arena* arena)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, _class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  SharedCtor(arena);
  // @@protoc_insertion_point(arena_constructor:my_grpc.GetVerifyRequest)
}
inline PROTOBUF_NDEBUG_INLINE GetVerifyRequest::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility, ::google::protobuf::Arena* arena,
    const Impl_& from, const ::my_grpc::GetVerifyRequest& from_msg)
      : phone_(arena, from.phone_),
        _cached_size_{0} {}

GetVerifyRequest::GetVerifyRequest(
    ::google::protobuf::Arena* arena,
    const GetVerifyRequest& from)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, _class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  GetVerifyRequest* const _this = this;
  (void)_this;
  _internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);
  new (&_impl_) Impl_(internal_visibility(), arena, from._impl_, from);

  // @@protoc_insertion_point(copy_constructor:my_grpc.GetVerifyRequest)
}
inline PROTOBUF_NDEBUG_INLINE GetVerifyRequest::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility,
    ::google::protobuf::Arena* arena)
      : phone_(arena),
        _cached_size_{0} {}

inline void GetVerifyRequest::SharedCtor(::_pb::Arena* arena) {
  new (&_impl_) Impl_(internal_visibility(), arena);
}
GetVerifyRequest::~GetVerifyRequest() {
  // @@protoc_insertion_point(destructor:my_grpc.GetVerifyRequest)
  SharedDtor(*this);
}
inline void GetVerifyRequest::SharedDtor(MessageLite& self) {
  GetVerifyRequest& this_ = static_cast<GetVerifyRequest&>(self);
  this_._internal_metadata_.Delete<::google::protobuf::UnknownFieldSet>();
  ABSL_DCHECK(this_.GetArena() == nullptr);
  this_._impl_.phone_.Destroy();
  this_._impl_.~Impl_();
}

inline void* GetVerifyRequest::PlacementNew_(const void*, void* mem,
                                        ::google::protobuf::Arena* arena) {
  return ::new (mem) GetVerifyRequest(arena);
}
constexpr auto GetVerifyRequest::InternalNewImpl_() {
  return ::google::protobuf::internal::MessageCreator::CopyInit(sizeof(GetVerifyRequest),
                                            alignof(GetVerifyRequest));
}
PROTOBUF_CONSTINIT
PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::google::protobuf::internal::ClassDataFull GetVerifyRequest::_class_data_ = {
    ::google::protobuf::internal::ClassData{
        &_GetVerifyRequest_default_instance_._instance,
        &_table_.header,
        nullptr,  // OnDemandRegisterArenaDtor
        nullptr,  // IsInitialized
        &GetVerifyRequest::MergeImpl,
        ::google::protobuf::Message::GetNewImpl<GetVerifyRequest>(),
#if defined(PROTOBUF_CUSTOM_VTABLE)
        &GetVerifyRequest::SharedDtor,
        ::google::protobuf::Message::GetClearImpl<GetVerifyRequest>(), &GetVerifyRequest::ByteSizeLong,
            &GetVerifyRequest::_InternalSerialize,
#endif  // PROTOBUF_CUSTOM_VTABLE
        PROTOBUF_FIELD_OFFSET(GetVerifyRequest, _impl_._cached_size_),
        false,
    },
    &GetVerifyRequest::kDescriptorMethods,
    &descriptor_table_my_5fgrpc_2eproto,
    nullptr,  // tracker
};
const ::google::protobuf::internal::ClassData* GetVerifyRequest::GetClassData() const {
  ::google::protobuf::internal::PrefetchToLocalCache(&_class_data_);
  ::google::protobuf::internal::PrefetchToLocalCache(_class_data_.tc_table);
  return _class_data_.base();
}
PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::_pbi::TcParseTable<0, 1, 0, 38, 2> GetVerifyRequest::_table_ = {
  {
    0,  // no _has_bits_
    0, // no _extensions_
    1, 0,  // max_field_number, fast_idx_mask
    offsetof(decltype(_table_), field_lookup_table),
    4294967294,  // skipmap
    offsetof(decltype(_table_), field_entries),
    1,  // num_field_entries
    0,  // num_aux_entries
    offsetof(decltype(_table_), field_names),  // no aux_entries
    _class_data_.base(),
    nullptr,  // post_loop_handler
    ::_pbi::TcParser::GenericFallback,  // fallback
    #ifdef PROTOBUF_PREFETCH_PARSE_TABLE
    ::_pbi::TcParser::GetTable<::my_grpc::GetVerifyRequest>(),  // to_prefetch
    #endif  // PROTOBUF_PREFETCH_PARSE_TABLE
  }, {{
    // string phone = 1;
    {::_pbi::TcParser::FastUS1,
     {10, 63, 0, PROTOBUF_FIELD_OFFSET(GetVerifyRequest, _impl_.phone_)}},
  }}, {{
    65535, 65535
  }}, {{
    // string phone = 1;
    {PROTOBUF_FIELD_OFFSET(GetVerifyRequest, _impl_.phone_), 0, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kUtf8String | ::_fl::kRepAString)},
  }},
  // no aux_entries
  {{
    "\30\5\0\0\0\0\0\0"
    "my_grpc.GetVerifyRequest"
    "phone"
  }},
};

PROTOBUF_NOINLINE void GetVerifyRequest::Clear() {
// @@protoc_insertion_point(message_clear_start:my_grpc.GetVerifyRequest)
  ::google::protobuf::internal::TSanWrite(&_impl_);
  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  _impl_.phone_.ClearToEmpty();
  _internal_metadata_.Clear<::google::protobuf::UnknownFieldSet>();
}

#if defined(PROTOBUF_CUSTOM_VTABLE)
        ::uint8_t* GetVerifyRequest::_InternalSerialize(
            const MessageLite& base, ::uint8_t* target,
            ::google::protobuf::io::EpsCopyOutputStream* stream) {
          const GetVerifyRequest& this_ = static_cast<const GetVerifyRequest&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
        ::uint8_t* GetVerifyRequest::_InternalSerialize(
            ::uint8_t* target,
            ::google::protobuf::io::EpsCopyOutputStream* stream) const {
          const GetVerifyRequest& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
          // @@protoc_insertion_point(serialize_to_array_start:my_grpc.GetVerifyRequest)
          ::uint32_t cached_has_bits = 0;
          (void)cached_has_bits;

          // string phone = 1;
          if (!this_._internal_phone().empty()) {
            const std::string& _s = this_._internal_phone();
            ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
                _s.data(), static_cast<int>(_s.length()), ::google::protobuf::internal::WireFormatLite::SERIALIZE, "my_grpc.GetVerifyRequest.phone");
            target = stream->WriteStringMaybeAliased(1, _s, target);
          }

          if (PROTOBUF_PREDICT_FALSE(this_._internal_metadata_.have_unknown_fields())) {
            target =
                ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
                    this_._internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance), target, stream);
          }
          // @@protoc_insertion_point(serialize_to_array_end:my_grpc.GetVerifyRequest)
          return target;
        }

#if defined(PROTOBUF_CUSTOM_VTABLE)
        ::size_t GetVerifyRequest::ByteSizeLong(const MessageLite& base) {
          const GetVerifyRequest& this_ = static_cast<const GetVerifyRequest&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
        ::size_t GetVerifyRequest::ByteSizeLong() const {
          const GetVerifyRequest& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
          // @@protoc_insertion_point(message_byte_size_start:my_grpc.GetVerifyRequest)
          ::size_t total_size = 0;

          ::uint32_t cached_has_bits = 0;
          // Prevent compiler warnings about cached_has_bits being unused
          (void)cached_has_bits;

           {
            // string phone = 1;
            if (!this_._internal_phone().empty()) {
              total_size += 1 + ::google::protobuf::internal::WireFormatLite::StringSize(
                                              this_._internal_phone());
            }
          }
          return this_.MaybeComputeUnknownFieldsSize(total_size,
                                                     &this_._impl_._cached_size_);
        }

void GetVerifyRequest::MergeImpl(::google::protobuf::MessageLite& to_msg, const ::google::protobuf::MessageLite& from_msg) {
  auto* const _this = static_cast<GetVerifyRequest*>(&to_msg);
  auto& from = static_cast<const GetVerifyRequest&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:my_grpc.GetVerifyRequest)
  ABSL_DCHECK_NE(&from, _this);
  ::uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  if (!from._internal_phone().empty()) {
    _this->_internal_set_phone(from._internal_phone());
  }
  _this->_internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(from._internal_metadata_);
}

void GetVerifyRequest::CopyFrom(const GetVerifyRequest& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:my_grpc.GetVerifyRequest)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}


void GetVerifyRequest::InternalSwap(GetVerifyRequest* PROTOBUF_RESTRICT other) {
  using std::swap;
  auto* arena = GetArena();
  ABSL_DCHECK_EQ(arena, other->GetArena());
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  ::_pbi::ArenaStringPtr::InternalSwap(&_impl_.phone_, &other->_impl_.phone_, arena);
}

::google::protobuf::Metadata GetVerifyRequest::GetMetadata() const {
  return ::google::protobuf::Message::GetMetadataImpl(GetClassData()->full());
}
// ===================================================================

class GetVerifyResponse::_Internal {
 public:
};

GetVerifyResponse::GetVerifyResponse(::google::protobuf::Arena* arena)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, _class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  SharedCtor(arena);
  // @@protoc_insertion_point(arena_constructor:my_grpc.GetVerifyResponse)
}
inline PROTOBUF_NDEBUG_INLINE GetVerifyResponse::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility, ::google::protobuf::Arena* arena,
    const Impl_& from, const ::my_grpc::GetVerifyResponse& from_msg)
      : phone_(arena, from.phone_),
        code_(arena, from.code_),
        _cached_size_{0} {}

GetVerifyResponse::GetVerifyResponse(
    ::google::protobuf::Arena* arena,
    const GetVerifyResponse& from)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, _class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  GetVerifyResponse* const _this = this;
  (void)_this;
  _internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);
  new (&_impl_) Impl_(internal_visibility(), arena, from._impl_, from);
  _impl_.error_ = from._impl_.error_;

  // @@protoc_insertion_point(copy_constructor:my_grpc.GetVerifyResponse)
}
inline PROTOBUF_NDEBUG_INLINE GetVerifyResponse::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility,
    ::google::protobuf::Arena* arena)
      : phone_(arena),
        code_(arena),
        _cached_size_{0} {}

inline void GetVerifyResponse::SharedCtor(::_pb::Arena* arena) {
  new (&_impl_) Impl_(internal_visibility(), arena);
  _impl_.error_ = {};
}
GetVerifyResponse::~GetVerifyResponse() {
  // @@protoc_insertion_point(destructor:my_grpc.GetVerifyResponse)
  SharedDtor(*this);
}
inline void GetVerifyResponse::SharedDtor(MessageLite& self) {
  GetVerifyResponse& this_ = static_cast<GetVerifyResponse&>(self);
  this_._internal_metadata_.Delete<::google::protobuf::UnknownFieldSet>();
  ABSL_DCHECK(this_.GetArena() == nullptr);
  this_._impl_.phone_.Destroy();
  this_._impl_.code_.Destroy();
  this_._impl_.~Impl_();
}

inline void* GetVerifyResponse::PlacementNew_(const void*, void* mem,
                                        ::google::protobuf::Arena* arena) {
  return ::new (mem) GetVerifyResponse(arena);
}
constexpr auto GetVerifyResponse::InternalNewImpl_() {
  return ::google::protobuf::internal::MessageCreator::CopyInit(sizeof(GetVerifyResponse),
                                            alignof(GetVerifyResponse));
}
PROTOBUF_CONSTINIT
PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::google::protobuf::internal::ClassDataFull GetVerifyResponse::_class_data_ = {
    ::google::protobuf::internal::ClassData{
        &_GetVerifyResponse_default_instance_._instance,
        &_table_.header,
        nullptr,  // OnDemandRegisterArenaDtor
        nullptr,  // IsInitialized
        &GetVerifyResponse::MergeImpl,
        ::google::protobuf::Message::GetNewImpl<GetVerifyResponse>(),
#if defined(PROTOBUF_CUSTOM_VTABLE)
        &GetVerifyResponse::SharedDtor,
        ::google::protobuf::Message::GetClearImpl<GetVerifyResponse>(), &GetVerifyResponse::ByteSizeLong,
            &GetVerifyResponse::_InternalSerialize,
#endif  // PROTOBUF_CUSTOM_VTABLE
        PROTOBUF_FIELD_OFFSET(GetVerifyResponse, _impl_._cached_size_),
        false,
    },
    &GetVerifyResponse::kDescriptorMethods,
    &descriptor_table_my_5fgrpc_2eproto,
    nullptr,  // tracker
};
const ::google::protobuf::internal::ClassData* GetVerifyResponse::GetClassData() const {
  ::google::protobuf::internal::PrefetchToLocalCache(&_class_data_);
  ::google::protobuf::internal::PrefetchToLocalCache(_class_data_.tc_table);
  return _class_data_.base();
}
PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::_pbi::TcParseTable<2, 3, 0, 43, 2> GetVerifyResponse::_table_ = {
  {
    0,  // no _has_bits_
    0, // no _extensions_
    3, 24,  // max_field_number, fast_idx_mask
    offsetof(decltype(_table_), field_lookup_table),
    4294967288,  // skipmap
    offsetof(decltype(_table_), field_entries),
    3,  // num_field_entries
    0,  // num_aux_entries
    offsetof(decltype(_table_), field_names),  // no aux_entries
    _class_data_.base(),
    nullptr,  // post_loop_handler
    ::_pbi::TcParser::GenericFallback,  // fallback
    #ifdef PROTOBUF_PREFETCH_PARSE_TABLE
    ::_pbi::TcParser::GetTable<::my_grpc::GetVerifyResponse>(),  // to_prefetch
    #endif  // PROTOBUF_PREFETCH_PARSE_TABLE
  }, {{
    {::_pbi::TcParser::MiniParse, {}},
    // int32 error = 1;
    {::_pbi::TcParser::SingularVarintNoZag1<::uint32_t, offsetof(GetVerifyResponse, _impl_.error_), 63>(),
     {8, 63, 0, PROTOBUF_FIELD_OFFSET(GetVerifyResponse, _impl_.error_)}},
    // string phone = 2;
    {::_pbi::TcParser::FastUS1,
     {18, 63, 0, PROTOBUF_FIELD_OFFSET(GetVerifyResponse, _impl_.phone_)}},
    // string code = 3;
    {::_pbi::TcParser::FastUS1,
     {26, 63, 0, PROTOBUF_FIELD_OFFSET(GetVerifyResponse, _impl_.code_)}},
  }}, {{
    65535, 65535
  }}, {{
    // int32 error = 1;
    {PROTOBUF_FIELD_OFFSET(GetVerifyResponse, _impl_.error_), 0, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kInt32)},
    // string phone = 2;
    {PROTOBUF_FIELD_OFFSET(GetVerifyResponse, _impl_.phone_), 0, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kUtf8String | ::_fl::kRepAString)},
    // string code = 3;
    {PROTOBUF_FIELD_OFFSET(GetVerifyResponse, _impl_.code_), 0, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kUtf8String | ::_fl::kRepAString)},
  }},
  // no aux_entries
  {{
    "\31\0\5\4\0\0\0\0"
    "my_grpc.GetVerifyResponse"
    "phone"
    "code"
  }},
};

PROTOBUF_NOINLINE void GetVerifyResponse::Clear() {
// @@protoc_insertion_point(message_clear_start:my_grpc.GetVerifyResponse)
  ::google::protobuf::internal::TSanWrite(&_impl_);
  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  _impl_.phone_.ClearToEmpty();
  _impl_.code_.ClearToEmpty();
  _impl_.error_ = 0;
  _internal_metadata_.Clear<::google::protobuf::UnknownFieldSet>();
}

#if defined(PROTOBUF_CUSTOM_VTABLE)
        ::uint8_t* GetVerifyResponse::_InternalSerialize(
            const MessageLite& base, ::uint8_t* target,
            ::google::protobuf::io::EpsCopyOutputStream* stream) {
          const GetVerifyResponse& this_ = static_cast<const GetVerifyResponse&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
        ::uint8_t* GetVerifyResponse::_InternalSerialize(
            ::uint8_t* target,
            ::google::protobuf::io::EpsCopyOutputStream* stream) const {
          const GetVerifyResponse& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
          // @@protoc_insertion_point(serialize_to_array_start:my_grpc.GetVerifyResponse)
          ::uint32_t cached_has_bits = 0;
          (void)cached_has_bits;

          // int32 error = 1;
          if (this_._internal_error() != 0) {
            target = ::google::protobuf::internal::WireFormatLite::
                WriteInt32ToArrayWithField<1>(
                    stream, this_._internal_error(), target);
          }

          // string phone = 2;
          if (!this_._internal_phone().empty()) {
            const std::string& _s = this_._internal_phone();
            ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
                _s.data(), static_cast<int>(_s.length()), ::google::protobuf::internal::WireFormatLite::SERIALIZE, "my_grpc.GetVerifyResponse.phone");
            target = stream->WriteStringMaybeAliased(2, _s, target);
          }

          // string code = 3;
          if (!this_._internal_code().empty()) {
            const std::string& _s = this_._internal_code();
            ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
                _s.data(), static_cast<int>(_s.length()), ::google::protobuf::internal::WireFormatLite::SERIALIZE, "my_grpc.GetVerifyResponse.code");
            target = stream->WriteStringMaybeAliased(3, _s, target);
          }

          if (PROTOBUF_PREDICT_FALSE(this_._internal_metadata_.have_unknown_fields())) {
            target =
                ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
                    this_._internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance), target, stream);
          }
          // @@protoc_insertion_point(serialize_to_array_end:my_grpc.GetVerifyResponse)
          return target;
        }

#if defined(PROTOBUF_CUSTOM_VTABLE)
        ::size_t GetVerifyResponse::ByteSizeLong(const MessageLite& base) {
          const GetVerifyResponse& this_ = static_cast<const GetVerifyResponse&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
        ::size_t GetVerifyResponse::ByteSizeLong() const {
          const GetVerifyResponse& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
          // @@protoc_insertion_point(message_byte_size_start:my_grpc.GetVerifyResponse)
          ::size_t total_size = 0;

          ::uint32_t cached_has_bits = 0;
          // Prevent compiler warnings about cached_has_bits being unused
          (void)cached_has_bits;

          ::_pbi::Prefetch5LinesFrom7Lines(&this_);
           {
            // string phone = 2;
            if (!this_._internal_phone().empty()) {
              total_size += 1 + ::google::protobuf::internal::WireFormatLite::StringSize(
                                              this_._internal_phone());
            }
            // string code = 3;
            if (!this_._internal_code().empty()) {
              total_size += 1 + ::google::protobuf::internal::WireFormatLite::StringSize(
                                              this_._internal_code());
            }
            // int32 error = 1;
            if (this_._internal_error() != 0) {
              total_size += ::_pbi::WireFormatLite::Int32SizePlusOne(
                  this_._internal_error());
            }
          }
          return this_.MaybeComputeUnknownFieldsSize(total_size,
                                                     &this_._impl_._cached_size_);
        }

void GetVerifyResponse::MergeImpl(::google::protobuf::MessageLite& to_msg, const ::google::protobuf::MessageLite& from_msg) {
  auto* const _this = static_cast<GetVerifyResponse*>(&to_msg);
  auto& from = static_cast<const GetVerifyResponse&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:my_grpc.GetVerifyResponse)
  ABSL_DCHECK_NE(&from, _this);
  ::uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  if (!from._internal_phone().empty()) {
    _this->_internal_set_phone(from._internal_phone());
  }
  if (!from._internal_code().empty()) {
    _this->_internal_set_code(from._internal_code());
  }
  if (from._internal_error() != 0) {
    _this->_impl_.error_ = from._impl_.error_;
  }
  _this->_internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(from._internal_metadata_);
}

void GetVerifyResponse::CopyFrom(const GetVerifyResponse& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:my_grpc.GetVerifyResponse)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}


void GetVerifyResponse::InternalSwap(GetVerifyResponse* PROTOBUF_RESTRICT other) {
  using std::swap;
  auto* arena = GetArena();
  ABSL_DCHECK_EQ(arena, other->GetArena());
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  ::_pbi::ArenaStringPtr::InternalSwap(&_impl_.phone_, &other->_impl_.phone_, arena);
  ::_pbi::ArenaStringPtr::InternalSwap(&_impl_.code_, &other->_impl_.code_, arena);
        swap(_impl_.error_, other->_impl_.error_);
}

::google::protobuf::Metadata GetVerifyResponse::GetMetadata() const {
  return ::google::protobuf::Message::GetMetadataImpl(GetClassData()->full());
}
// ===================================================================

class GetChatServerRequest::_Internal {
 public:
};

GetChatServerRequest::GetChatServerRequest(::google::protobuf::Arena* arena)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, _class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  SharedCtor(arena);
  // @@protoc_insertion_point(arena_constructor:my_grpc.GetChatServerRequest)
}
inline PROTOBUF_NDEBUG_INLINE GetChatServerRequest::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility, ::google::protobuf::Arena* arena,
    const Impl_& from, const ::my_grpc::GetChatServerRequest& from_msg)
      : uid_(arena, from.uid_),
        _cached_size_{0} {}

GetChatServerRequest::GetChatServerRequest(
    ::google::protobuf::Arena* arena,
    const GetChatServerRequest& from)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, _class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  GetChatServerRequest* const _this = this;
  (void)_this;
  _internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);
  new (&_impl_) Impl_(internal_visibility(), arena, from._impl_, from);

  // @@protoc_insertion_point(copy_constructor:my_grpc.GetChatServerRequest)
}
inline PROTOBUF_NDEBUG_INLINE GetChatServerRequest::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility,
    ::google::protobuf::Arena* arena)
      : uid_(arena),
        _cached_size_{0} {}

inline void GetChatServerRequest::SharedCtor(::_pb::Arena* arena) {
  new (&_impl_) Impl_(internal_visibility(), arena);
}
GetChatServerRequest::~GetChatServerRequest() {
  // @@protoc_insertion_point(destructor:my_grpc.GetChatServerRequest)
  SharedDtor(*this);
}
inline void GetChatServerRequest::SharedDtor(MessageLite& self) {
  GetChatServerRequest& this_ = static_cast<GetChatServerRequest&>(self);
  this_._internal_metadata_.Delete<::google::protobuf::UnknownFieldSet>();
  ABSL_DCHECK(this_.GetArena() == nullptr);
  this_._impl_.uid_.Destroy();
  this_._impl_.~Impl_();
}

inline void* GetChatServerRequest::PlacementNew_(const void*, void* mem,
                                        ::google::protobuf::Arena* arena) {
  return ::new (mem) GetChatServerRequest(arena);
}
constexpr auto GetChatServerRequest::InternalNewImpl_() {
  return ::google::protobuf::internal::MessageCreator::CopyInit(sizeof(GetChatServerRequest),
                                            alignof(GetChatServerRequest));
}
PROTOBUF_CONSTINIT
PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::google::protobuf::internal::ClassDataFull GetChatServerRequest::_class_data_ = {
    ::google::protobuf::internal::ClassData{
        &_GetChatServerRequest_default_instance_._instance,
        &_table_.header,
        nullptr,  // OnDemandRegisterArenaDtor
        nullptr,  // IsInitialized
        &GetChatServerRequest::MergeImpl,
        ::google::protobuf::Message::GetNewImpl<GetChatServerRequest>(),
#if defined(PROTOBUF_CUSTOM_VTABLE)
        &GetChatServerRequest::SharedDtor,
        ::google::protobuf::Message::GetClearImpl<GetChatServerRequest>(), &GetChatServerRequest::ByteSizeLong,
            &GetChatServerRequest::_InternalSerialize,
#endif  // PROTOBUF_CUSTOM_VTABLE
        PROTOBUF_FIELD_OFFSET(GetChatServerRequest, _impl_._cached_size_),
        false,
    },
    &GetChatServerRequest::kDescriptorMethods,
    &descriptor_table_my_5fgrpc_2eproto,
    nullptr,  // tracker
};
const ::google::protobuf::internal::ClassData* GetChatServerRequest::GetClassData() const {
  ::google::protobuf::internal::PrefetchToLocalCache(&_class_data_);
  ::google::protobuf::internal::PrefetchToLocalCache(_class_data_.tc_table);
  return _class_data_.base();
}
PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::_pbi::TcParseTable<0, 1, 0, 40, 2> GetChatServerRequest::_table_ = {
  {
    0,  // no _has_bits_
    0, // no _extensions_
    1, 0,  // max_field_number, fast_idx_mask
    offsetof(decltype(_table_), field_lookup_table),
    4294967294,  // skipmap
    offsetof(decltype(_table_), field_entries),
    1,  // num_field_entries
    0,  // num_aux_entries
    offsetof(decltype(_table_), field_names),  // no aux_entries
    _class_data_.base(),
    nullptr,  // post_loop_handler
    ::_pbi::TcParser::GenericFallback,  // fallback
    #ifdef PROTOBUF_PREFETCH_PARSE_TABLE
    ::_pbi::TcParser::GetTable<::my_grpc::GetChatServerRequest>(),  // to_prefetch
    #endif  // PROTOBUF_PREFETCH_PARSE_TABLE
  }, {{
    // string uid = 1;
    {::_pbi::TcParser::FastUS1,
     {10, 63, 0, PROTOBUF_FIELD_OFFSET(GetChatServerRequest, _impl_.uid_)}},
  }}, {{
    65535, 65535
  }}, {{
    // string uid = 1;
    {PROTOBUF_FIELD_OFFSET(GetChatServerRequest, _impl_.uid_), 0, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kUtf8String | ::_fl::kRepAString)},
  }},
  // no aux_entries
  {{
    "\34\3\0\0\0\0\0\0"
    "my_grpc.GetChatServerRequest"
    "uid"
  }},
};

PROTOBUF_NOINLINE void GetChatServerRequest::Clear() {
// @@protoc_insertion_point(message_clear_start:my_grpc.GetChatServerRequest)
  ::google::protobuf::internal::TSanWrite(&_impl_);
  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  _impl_.uid_.ClearToEmpty();
  _internal_metadata_.Clear<::google::protobuf::UnknownFieldSet>();
}

#if defined(PROTOBUF_CUSTOM_VTABLE)
        ::uint8_t* GetChatServerRequest::_InternalSerialize(
            const MessageLite& base, ::uint8_t* target,
            ::google::protobuf::io::EpsCopyOutputStream* stream) {
          const GetChatServerRequest& this_ = static_cast<const GetChatServerRequest&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
        ::uint8_t* GetChatServerRequest::_InternalSerialize(
            ::uint8_t* target,
            ::google::protobuf::io::EpsCopyOutputStream* stream) const {
          const GetChatServerRequest& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
          // @@protoc_insertion_point(serialize_to_array_start:my_grpc.GetChatServerRequest)
          ::uint32_t cached_has_bits = 0;
          (void)cached_has_bits;

          // string uid = 1;
          if (!this_._internal_uid().empty()) {
            const std::string& _s = this_._internal_uid();
            ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
                _s.data(), static_cast<int>(_s.length()), ::google::protobuf::internal::WireFormatLite::SERIALIZE, "my_grpc.GetChatServerRequest.uid");
            target = stream->WriteStringMaybeAliased(1, _s, target);
          }

          if (PROTOBUF_PREDICT_FALSE(this_._internal_metadata_.have_unknown_fields())) {
            target =
                ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
                    this_._internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance), target, stream);
          }
          // @@protoc_insertion_point(serialize_to_array_end:my_grpc.GetChatServerRequest)
          return target;
        }

#if defined(PROTOBUF_CUSTOM_VTABLE)
        ::size_t GetChatServerRequest::ByteSizeLong(const MessageLite& base) {
          const GetChatServerRequest& this_ = static_cast<const GetChatServerRequest&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
        ::size_t GetChatServerRequest::ByteSizeLong() const {
          const GetChatServerRequest& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
          // @@protoc_insertion_point(message_byte_size_start:my_grpc.GetChatServerRequest)
          ::size_t total_size = 0;

          ::uint32_t cached_has_bits = 0;
          // Prevent compiler warnings about cached_has_bits being unused
          (void)cached_has_bits;

           {
            // string uid = 1;
            if (!this_._internal_uid().empty()) {
              total_size += 1 + ::google::protobuf::internal::WireFormatLite::StringSize(
                                              this_._internal_uid());
            }
          }
          return this_.MaybeComputeUnknownFieldsSize(total_size,
                                                     &this_._impl_._cached_size_);
        }

void GetChatServerRequest::MergeImpl(::google::protobuf::MessageLite& to_msg, const ::google::protobuf::MessageLite& from_msg) {
  auto* const _this = static_cast<GetChatServerRequest*>(&to_msg);
  auto& from = static_cast<const GetChatServerRequest&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:my_grpc.GetChatServerRequest)
  ABSL_DCHECK_NE(&from, _this);
  ::uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  if (!from._internal_uid().empty()) {
    _this->_internal_set_uid(from._internal_uid());
  }
  _this->_internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(from._internal_metadata_);
}

void GetChatServerRequest::CopyFrom(const GetChatServerRequest& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:my_grpc.GetChatServerRequest)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}


void GetChatServerRequest::InternalSwap(GetChatServerRequest* PROTOBUF_RESTRICT other) {
  using std::swap;
  auto* arena = GetArena();
  ABSL_DCHECK_EQ(arena, other->GetArena());
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  ::_pbi::ArenaStringPtr::InternalSwap(&_impl_.uid_, &other->_impl_.uid_, arena);
}

::google::protobuf::Metadata GetChatServerRequest::GetMetadata() const {
  return ::google::protobuf::Message::GetMetadataImpl(GetClassData()->full());
}
// ===================================================================

class GetChatServerResponse::_Internal {
 public:
};

GetChatServerResponse::GetChatServerResponse(::google::protobuf::Arena* arena)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, _class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  SharedCtor(arena);
  // @@protoc_insertion_point(arena_constructor:my_grpc.GetChatServerResponse)
}
inline PROTOBUF_NDEBUG_INLINE GetChatServerResponse::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility, ::google::protobuf::Arena* arena,
    const Impl_& from, const ::my_grpc::GetChatServerResponse& from_msg)
      : host_(arena, from.host_),
        token_(arena, from.token_),
        _cached_size_{0} {}

GetChatServerResponse::GetChatServerResponse(
    ::google::protobuf::Arena* arena,
    const GetChatServerResponse& from)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, _class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  GetChatServerResponse* const _this = this;
  (void)_this;
  _internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);
  new (&_impl_) Impl_(internal_visibility(), arena, from._impl_, from);
  ::memcpy(reinterpret_cast<char *>(&_impl_) +
               offsetof(Impl_, error_),
           reinterpret_cast<const char *>(&from._impl_) +
               offsetof(Impl_, error_),
           offsetof(Impl_, port_) -
               offsetof(Impl_, error_) +
               sizeof(Impl_::port_));

  // @@protoc_insertion_point(copy_constructor:my_grpc.GetChatServerResponse)
}
inline PROTOBUF_NDEBUG_INLINE GetChatServerResponse::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility,
    ::google::protobuf::Arena* arena)
      : host_(arena),
        token_(arena),
        _cached_size_{0} {}

inline void GetChatServerResponse::SharedCtor(::_pb::Arena* arena) {
  new (&_impl_) Impl_(internal_visibility(), arena);
  ::memset(reinterpret_cast<char *>(&_impl_) +
               offsetof(Impl_, error_),
           0,
           offsetof(Impl_, port_) -
               offsetof(Impl_, error_) +
               sizeof(Impl_::port_));
}
GetChatServerResponse::~GetChatServerResponse() {
  // @@protoc_insertion_point(destructor:my_grpc.GetChatServerResponse)
  SharedDtor(*this);
}
inline void GetChatServerResponse::SharedDtor(MessageLite& self) {
  GetChatServerResponse& this_ = static_cast<GetChatServerResponse&>(self);
  this_._internal_metadata_.Delete<::google::protobuf::UnknownFieldSet>();
  ABSL_DCHECK(this_.GetArena() == nullptr);
  this_._impl_.host_.Destroy();
  this_._impl_.token_.Destroy();
  this_._impl_.~Impl_();
}

inline void* GetChatServerResponse::PlacementNew_(const void*, void* mem,
                                        ::google::protobuf::Arena* arena) {
  return ::new (mem) GetChatServerResponse(arena);
}
constexpr auto GetChatServerResponse::InternalNewImpl_() {
  return ::google::protobuf::internal::MessageCreator::CopyInit(sizeof(GetChatServerResponse),
                                            alignof(GetChatServerResponse));
}
PROTOBUF_CONSTINIT
PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::google::protobuf::internal::ClassDataFull GetChatServerResponse::_class_data_ = {
    ::google::protobuf::internal::ClassData{
        &_GetChatServerResponse_default_instance_._instance,
        &_table_.header,
        nullptr,  // OnDemandRegisterArenaDtor
        nullptr,  // IsInitialized
        &GetChatServerResponse::MergeImpl,
        ::google::protobuf::Message::GetNewImpl<GetChatServerResponse>(),
#if defined(PROTOBUF_CUSTOM_VTABLE)
        &GetChatServerResponse::SharedDtor,
        ::google::protobuf::Message::GetClearImpl<GetChatServerResponse>(), &GetChatServerResponse::ByteSizeLong,
            &GetChatServerResponse::_InternalSerialize,
#endif  // PROTOBUF_CUSTOM_VTABLE
        PROTOBUF_FIELD_OFFSET(GetChatServerResponse, _impl_._cached_size_),
        false,
    },
    &GetChatServerResponse::kDescriptorMethods,
    &descriptor_table_my_5fgrpc_2eproto,
    nullptr,  // tracker
};
const ::google::protobuf::internal::ClassData* GetChatServerResponse::GetClassData() const {
  ::google::protobuf::internal::PrefetchToLocalCache(&_class_data_);
  ::google::protobuf::internal::PrefetchToLocalCache(_class_data_.tc_table);
  return _class_data_.base();
}
PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::_pbi::TcParseTable<2, 4, 0, 47, 2> GetChatServerResponse::_table_ = {
  {
    0,  // no _has_bits_
    0, // no _extensions_
    4, 24,  // max_field_number, fast_idx_mask
    offsetof(decltype(_table_), field_lookup_table),
    4294967280,  // skipmap
    offsetof(decltype(_table_), field_entries),
    4,  // num_field_entries
    0,  // num_aux_entries
    offsetof(decltype(_table_), field_names),  // no aux_entries
    _class_data_.base(),
    nullptr,  // post_loop_handler
    ::_pbi::TcParser::GenericFallback,  // fallback
    #ifdef PROTOBUF_PREFETCH_PARSE_TABLE
    ::_pbi::TcParser::GetTable<::my_grpc::GetChatServerResponse>(),  // to_prefetch
    #endif  // PROTOBUF_PREFETCH_PARSE_TABLE
  }, {{
    // string token = 4;
    {::_pbi::TcParser::FastUS1,
     {34, 63, 0, PROTOBUF_FIELD_OFFSET(GetChatServerResponse, _impl_.token_)}},
    // int32 error = 1;
    {::_pbi::TcParser::SingularVarintNoZag1<::uint32_t, offsetof(GetChatServerResponse, _impl_.error_), 63>(),
     {8, 63, 0, PROTOBUF_FIELD_OFFSET(GetChatServerResponse, _impl_.error_)}},
    // string host = 2;
    {::_pbi::TcParser::FastUS1,
     {18, 63, 0, PROTOBUF_FIELD_OFFSET(GetChatServerResponse, _impl_.host_)}},
    // int32 port = 3;
    {::_pbi::TcParser::SingularVarintNoZag1<::uint32_t, offsetof(GetChatServerResponse, _impl_.port_), 63>(),
     {24, 63, 0, PROTOBUF_FIELD_OFFSET(GetChatServerResponse, _impl_.port_)}},
  }}, {{
    65535, 65535
  }}, {{
    // int32 error = 1;
    {PROTOBUF_FIELD_OFFSET(GetChatServerResponse, _impl_.error_), 0, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kInt32)},
    // string host = 2;
    {PROTOBUF_FIELD_OFFSET(GetChatServerResponse, _impl_.host_), 0, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kUtf8String | ::_fl::kRepAString)},
    // int32 port = 3;
    {PROTOBUF_FIELD_OFFSET(GetChatServerResponse, _impl_.port_), 0, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kInt32)},
    // string token = 4;
    {PROTOBUF_FIELD_OFFSET(GetChatServerResponse, _impl_.token_), 0, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kUtf8String | ::_fl::kRepAString)},
  }},
  // no aux_entries
  {{
    "\35\0\4\0\5\0\0\0"
    "my_grpc.GetChatServerResponse"
    "host"
    "token"
  }},
};

PROTOBUF_NOINLINE void GetChatServerResponse::Clear() {
// @@protoc_insertion_point(message_clear_start:my_grpc.GetChatServerResponse)
  ::google::protobuf::internal::TSanWrite(&_impl_);
  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  _impl_.host_.ClearToEmpty();
  _impl_.token_.ClearToEmpty();
  ::memset(&_impl_.error_, 0, static_cast<::size_t>(
      reinterpret_cast<char*>(&_impl_.port_) -
      reinterpret_cast<char*>(&_impl_.error_)) + sizeof(_impl_.port_));
  _internal_metadata_.Clear<::google::protobuf::UnknownFieldSet>();
}

#if defined(PROTOBUF_CUSTOM_VTABLE)
        ::uint8_t* GetChatServerResponse::_InternalSerialize(
            const MessageLite& base, ::uint8_t* target,
            ::google::protobuf::io::EpsCopyOutputStream* stream) {
          const GetChatServerResponse& this_ = static_cast<const GetChatServerResponse&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
        ::uint8_t* GetChatServerResponse::_InternalSerialize(
            ::uint8_t* target,
            ::google::protobuf::io::EpsCopyOutputStream* stream) const {
          const GetChatServerResponse& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
          // @@protoc_insertion_point(serialize_to_array_start:my_grpc.GetChatServerResponse)
          ::uint32_t cached_has_bits = 0;
          (void)cached_has_bits;

          // int32 error = 1;
          if (this_._internal_error() != 0) {
            target = ::google::protobuf::internal::WireFormatLite::
                WriteInt32ToArrayWithField<1>(
                    stream, this_._internal_error(), target);
          }

          // string host = 2;
          if (!this_._internal_host().empty()) {
            const std::string& _s = this_._internal_host();
            ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
                _s.data(), static_cast<int>(_s.length()), ::google::protobuf::internal::WireFormatLite::SERIALIZE, "my_grpc.GetChatServerResponse.host");
            target = stream->WriteStringMaybeAliased(2, _s, target);
          }

          // int32 port = 3;
          if (this_._internal_port() != 0) {
            target = ::google::protobuf::internal::WireFormatLite::
                WriteInt32ToArrayWithField<3>(
                    stream, this_._internal_port(), target);
          }

          // string token = 4;
          if (!this_._internal_token().empty()) {
            const std::string& _s = this_._internal_token();
            ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
                _s.data(), static_cast<int>(_s.length()), ::google::protobuf::internal::WireFormatLite::SERIALIZE, "my_grpc.GetChatServerResponse.token");
            target = stream->WriteStringMaybeAliased(4, _s, target);
          }

          if (PROTOBUF_PREDICT_FALSE(this_._internal_metadata_.have_unknown_fields())) {
            target =
                ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
                    this_._internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance), target, stream);
          }
          // @@protoc_insertion_point(serialize_to_array_end:my_grpc.GetChatServerResponse)
          return target;
        }

#if defined(PROTOBUF_CUSTOM_VTABLE)
        ::size_t GetChatServerResponse::ByteSizeLong(const MessageLite& base) {
          const GetChatServerResponse& this_ = static_cast<const GetChatServerResponse&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
        ::size_t GetChatServerResponse::ByteSizeLong() const {
          const GetChatServerResponse& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
          // @@protoc_insertion_point(message_byte_size_start:my_grpc.GetChatServerResponse)
          ::size_t total_size = 0;

          ::uint32_t cached_has_bits = 0;
          // Prevent compiler warnings about cached_has_bits being unused
          (void)cached_has_bits;

          ::_pbi::Prefetch5LinesFrom7Lines(&this_);
           {
            // string host = 2;
            if (!this_._internal_host().empty()) {
              total_size += 1 + ::google::protobuf::internal::WireFormatLite::StringSize(
                                              this_._internal_host());
            }
            // string token = 4;
            if (!this_._internal_token().empty()) {
              total_size += 1 + ::google::protobuf::internal::WireFormatLite::StringSize(
                                              this_._internal_token());
            }
            // int32 error = 1;
            if (this_._internal_error() != 0) {
              total_size += ::_pbi::WireFormatLite::Int32SizePlusOne(
                  this_._internal_error());
            }
            // int32 port = 3;
            if (this_._internal_port() != 0) {
              total_size += ::_pbi::WireFormatLite::Int32SizePlusOne(
                  this_._internal_port());
            }
          }
          return this_.MaybeComputeUnknownFieldsSize(total_size,
                                                     &this_._impl_._cached_size_);
        }

void GetChatServerResponse::MergeImpl(::google::protobuf::MessageLite& to_msg, const ::google::protobuf::MessageLite& from_msg) {
  auto* const _this = static_cast<GetChatServerResponse*>(&to_msg);
  auto& from = static_cast<const GetChatServerResponse&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:my_grpc.GetChatServerResponse)
  ABSL_DCHECK_NE(&from, _this);
  ::uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  if (!from._internal_host().empty()) {
    _this->_internal_set_host(from._internal_host());
  }
  if (!from._internal_token().empty()) {
    _this->_internal_set_token(from._internal_token());
  }
  if (from._internal_error() != 0) {
    _this->_impl_.error_ = from._impl_.error_;
  }
  if (from._internal_port() != 0) {
    _this->_impl_.port_ = from._impl_.port_;
  }
  _this->_internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(from._internal_metadata_);
}

void GetChatServerResponse::CopyFrom(const GetChatServerResponse& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:my_grpc.GetChatServerResponse)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}


void GetChatServerResponse::InternalSwap(GetChatServerResponse* PROTOBUF_RESTRICT other) {
  using std::swap;
  auto* arena = GetArena();
  ABSL_DCHECK_EQ(arena, other->GetArena());
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  ::_pbi::ArenaStringPtr::InternalSwap(&_impl_.host_, &other->_impl_.host_, arena);
  ::_pbi::ArenaStringPtr::InternalSwap(&_impl_.token_, &other->_impl_.token_, arena);
  ::google::protobuf::internal::memswap<
      PROTOBUF_FIELD_OFFSET(GetChatServerResponse, _impl_.port_)
      + sizeof(GetChatServerResponse::_impl_.port_)
      - PROTOBUF_FIELD_OFFSET(GetChatServerResponse, _impl_.error_)>(
          reinterpret_cast<char*>(&_impl_.error_),
          reinterpret_cast<char*>(&other->_impl_.error_));
}

::google::protobuf::Metadata GetChatServerResponse::GetMetadata() const {
  return ::google::protobuf::Message::GetMetadataImpl(GetClassData()->full());
}
// ===================================================================

class UserLoginRequest::_Internal {
 public:
};

UserLoginRequest::UserLoginRequest(::google::protobuf::Arena* arena)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, _class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  SharedCtor(arena);
  // @@protoc_insertion_point(arena_constructor:my_grpc.UserLoginRequest)
}
inline PROTOBUF_NDEBUG_INLINE UserLoginRequest::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility, ::google::protobuf::Arena* arena,
    const Impl_& from, const ::my_grpc::UserLoginRequest& from_msg)
      : uid_(arena, from.uid_),
        token_(arena, from.token_),
        _cached_size_{0} {}

UserLoginRequest::UserLoginRequest(
    ::google::protobuf::Arena* arena,
    const UserLoginRequest& from)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, _class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  UserLoginRequest* const _this = this;
  (void)_this;
  _internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);
  new (&_impl_) Impl_(internal_visibility(), arena, from._impl_, from);

  // @@protoc_insertion_point(copy_constructor:my_grpc.UserLoginRequest)
}
inline PROTOBUF_NDEBUG_INLINE UserLoginRequest::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility,
    ::google::protobuf::Arena* arena)
      : uid_(arena),
        token_(arena),
        _cached_size_{0} {}

inline void UserLoginRequest::SharedCtor(::_pb::Arena* arena) {
  new (&_impl_) Impl_(internal_visibility(), arena);
}
UserLoginRequest::~UserLoginRequest() {
  // @@protoc_insertion_point(destructor:my_grpc.UserLoginRequest)
  SharedDtor(*this);
}
inline void UserLoginRequest::SharedDtor(MessageLite& self) {
  UserLoginRequest& this_ = static_cast<UserLoginRequest&>(self);
  this_._internal_metadata_.Delete<::google::protobuf::UnknownFieldSet>();
  ABSL_DCHECK(this_.GetArena() == nullptr);
  this_._impl_.uid_.Destroy();
  this_._impl_.token_.Destroy();
  this_._impl_.~Impl_();
}

inline void* UserLoginRequest::PlacementNew_(const void*, void* mem,
                                        ::google::protobuf::Arena* arena) {
  return ::new (mem) UserLoginRequest(arena);
}
constexpr auto UserLoginRequest::InternalNewImpl_() {
  return ::google::protobuf::internal::MessageCreator::CopyInit(sizeof(UserLoginRequest),
                                            alignof(UserLoginRequest));
}
PROTOBUF_CONSTINIT
PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::google::protobuf::internal::ClassDataFull UserLoginRequest::_class_data_ = {
    ::google::protobuf::internal::ClassData{
        &_UserLoginRequest_default_instance_._instance,
        &_table_.header,
        nullptr,  // OnDemandRegisterArenaDtor
        nullptr,  // IsInitialized
        &UserLoginRequest::MergeImpl,
        ::google::protobuf::Message::GetNewImpl<UserLoginRequest>(),
#if defined(PROTOBUF_CUSTOM_VTABLE)
        &UserLoginRequest::SharedDtor,
        ::google::protobuf::Message::GetClearImpl<UserLoginRequest>(), &UserLoginRequest::ByteSizeLong,
            &UserLoginRequest::_InternalSerialize,
#endif  // PROTOBUF_CUSTOM_VTABLE
        PROTOBUF_FIELD_OFFSET(UserLoginRequest, _impl_._cached_size_),
        false,
    },
    &UserLoginRequest::kDescriptorMethods,
    &descriptor_table_my_5fgrpc_2eproto,
    nullptr,  // tracker
};
const ::google::protobuf::internal::ClassData* UserLoginRequest::GetClassData() const {
  ::google::protobuf::internal::PrefetchToLocalCache(&_class_data_);
  ::google::protobuf::internal::PrefetchToLocalCache(_class_data_.tc_table);
  return _class_data_.base();
}
PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::_pbi::TcParseTable<1, 2, 0, 41, 2> UserLoginRequest::_table_ = {
  {
    0,  // no _has_bits_
    0, // no _extensions_
    2, 8,  // max_field_number, fast_idx_mask
    offsetof(decltype(_table_), field_lookup_table),
    4294967292,  // skipmap
    offsetof(decltype(_table_), field_entries),
    2,  // num_field_entries
    0,  // num_aux_entries
    offsetof(decltype(_table_), field_names),  // no aux_entries
    _class_data_.base(),
    nullptr,  // post_loop_handler
    ::_pbi::TcParser::GenericFallback,  // fallback
    #ifdef PROTOBUF_PREFETCH_PARSE_TABLE
    ::_pbi::TcParser::GetTable<::my_grpc::UserLoginRequest>(),  // to_prefetch
    #endif  // PROTOBUF_PREFETCH_PARSE_TABLE
  }, {{
    // string token = 2;
    {::_pbi::TcParser::FastUS1,
     {18, 63, 0, PROTOBUF_FIELD_OFFSET(UserLoginRequest, _impl_.token_)}},
    // string uid = 1;
    {::_pbi::TcParser::FastUS1,
     {10, 63, 0, PROTOBUF_FIELD_OFFSET(UserLoginRequest, _impl_.uid_)}},
  }}, {{
    65535, 65535
  }}, {{
    // string uid = 1;
    {PROTOBUF_FIELD_OFFSET(UserLoginRequest, _impl_.uid_), 0, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kUtf8String | ::_fl::kRepAString)},
    // string token = 2;
    {PROTOBUF_FIELD_OFFSET(UserLoginRequest, _impl_.token_), 0, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kUtf8String | ::_fl::kRepAString)},
  }},
  // no aux_entries
  {{
    "\30\3\5\0\0\0\0\0"
    "my_grpc.UserLoginRequest"
    "uid"
    "token"
  }},
};

PROTOBUF_NOINLINE void UserLoginRequest::Clear() {
// @@protoc_insertion_point(message_clear_start:my_grpc.UserLoginRequest)
  ::google::protobuf::internal::TSanWrite(&_impl_);
  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  _impl_.uid_.ClearToEmpty();
  _impl_.token_.ClearToEmpty();
  _internal_metadata_.Clear<::google::protobuf::UnknownFieldSet>();
}

#if defined(PROTOBUF_CUSTOM_VTABLE)
        ::uint8_t* UserLoginRequest::_InternalSerialize(
            const MessageLite& base, ::uint8_t* target,
            ::google::protobuf::io::EpsCopyOutputStream* stream) {
          const UserLoginRequest& this_ = static_cast<const UserLoginRequest&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
        ::uint8_t* UserLoginRequest::_InternalSerialize(
            ::uint8_t* target,
            ::google::protobuf::io::EpsCopyOutputStream* stream) const {
          const UserLoginRequest& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
          // @@protoc_insertion_point(serialize_to_array_start:my_grpc.UserLoginRequest)
          ::uint32_t cached_has_bits = 0;
          (void)cached_has_bits;

          // string uid = 1;
          if (!this_._internal_uid().empty()) {
            const std::string& _s = this_._internal_uid();
            ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
                _s.data(), static_cast<int>(_s.length()), ::google::protobuf::internal::WireFormatLite::SERIALIZE, "my_grpc.UserLoginRequest.uid");
            target = stream->WriteStringMaybeAliased(1, _s, target);
          }

          // string token = 2;
          if (!this_._internal_token().empty()) {
            const std::string& _s = this_._internal_token();
            ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
                _s.data(), static_cast<int>(_s.length()), ::google::protobuf::internal::WireFormatLite::SERIALIZE, "my_grpc.UserLoginRequest.token");
            target = stream->WriteStringMaybeAliased(2, _s, target);
          }

          if (PROTOBUF_PREDICT_FALSE(this_._internal_metadata_.have_unknown_fields())) {
            target =
                ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
                    this_._internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance), target, stream);
          }
          // @@protoc_insertion_point(serialize_to_array_end:my_grpc.UserLoginRequest)
          return target;
        }

#if defined(PROTOBUF_CUSTOM_VTABLE)
        ::size_t UserLoginRequest::ByteSizeLong(const MessageLite& base) {
          const UserLoginRequest& this_ = static_cast<const UserLoginRequest&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
        ::size_t UserLoginRequest::ByteSizeLong() const {
          const UserLoginRequest& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
          // @@protoc_insertion_point(message_byte_size_start:my_grpc.UserLoginRequest)
          ::size_t total_size = 0;

          ::uint32_t cached_has_bits = 0;
          // Prevent compiler warnings about cached_has_bits being unused
          (void)cached_has_bits;

          ::_pbi::Prefetch5LinesFrom7Lines(&this_);
           {
            // string uid = 1;
            if (!this_._internal_uid().empty()) {
              total_size += 1 + ::google::protobuf::internal::WireFormatLite::StringSize(
                                              this_._internal_uid());
            }
            // string token = 2;
            if (!this_._internal_token().empty()) {
              total_size += 1 + ::google::protobuf::internal::WireFormatLite::StringSize(
                                              this_._internal_token());
            }
          }
          return this_.MaybeComputeUnknownFieldsSize(total_size,
                                                     &this_._impl_._cached_size_);
        }

void UserLoginRequest::MergeImpl(::google::protobuf::MessageLite& to_msg, const ::google::protobuf::MessageLite& from_msg) {
  auto* const _this = static_cast<UserLoginRequest*>(&to_msg);
  auto& from = static_cast<const UserLoginRequest&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:my_grpc.UserLoginRequest)
  ABSL_DCHECK_NE(&from, _this);
  ::uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  if (!from._internal_uid().empty()) {
    _this->_internal_set_uid(from._internal_uid());
  }
  if (!from._internal_token().empty()) {
    _this->_internal_set_token(from._internal_token());
  }
  _this->_internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(from._internal_metadata_);
}

void UserLoginRequest::CopyFrom(const UserLoginRequest& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:my_grpc.UserLoginRequest)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}


void UserLoginRequest::InternalSwap(UserLoginRequest* PROTOBUF_RESTRICT other) {
  using std::swap;
  auto* arena = GetArena();
  ABSL_DCHECK_EQ(arena, other->GetArena());
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  ::_pbi::ArenaStringPtr::InternalSwap(&_impl_.uid_, &other->_impl_.uid_, arena);
  ::_pbi::ArenaStringPtr::InternalSwap(&_impl_.token_, &other->_impl_.token_, arena);
}

::google::protobuf::Metadata UserLoginRequest::GetMetadata() const {
  return ::google::protobuf::Message::GetMetadataImpl(GetClassData()->full());
}
// ===================================================================

class UserLoginResponse::_Internal {
 public:
};

UserLoginResponse::UserLoginResponse(::google::protobuf::Arena* arena)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, _class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  SharedCtor(arena);
  // @@protoc_insertion_point(arena_constructor:my_grpc.UserLoginResponse)
}
inline PROTOBUF_NDEBUG_INLINE UserLoginResponse::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility, ::google::protobuf::Arena* arena,
    const Impl_& from, const ::my_grpc::UserLoginResponse& from_msg)
      : uid_(arena, from.uid_),
        token_(arena, from.token_),
        _cached_size_{0} {}

UserLoginResponse::UserLoginResponse(
    ::google::protobuf::Arena* arena,
    const UserLoginResponse& from)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, _class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  UserLoginResponse* const _this = this;
  (void)_this;
  _internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);
  new (&_impl_) Impl_(internal_visibility(), arena, from._impl_, from);
  _impl_.error_ = from._impl_.error_;

  // @@protoc_insertion_point(copy_constructor:my_grpc.UserLoginResponse)
}
inline PROTOBUF_NDEBUG_INLINE UserLoginResponse::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility,
    ::google::protobuf::Arena* arena)
      : uid_(arena),
        token_(arena),
        _cached_size_{0} {}

inline void UserLoginResponse::SharedCtor(::_pb::Arena* arena) {
  new (&_impl_) Impl_(internal_visibility(), arena);
  _impl_.error_ = {};
}
UserLoginResponse::~UserLoginResponse() {
  // @@protoc_insertion_point(destructor:my_grpc.UserLoginResponse)
  SharedDtor(*this);
}
inline void UserLoginResponse::SharedDtor(MessageLite& self) {
  UserLoginResponse& this_ = static_cast<UserLoginResponse&>(self);
  this_._internal_metadata_.Delete<::google::protobuf::UnknownFieldSet>();
  ABSL_DCHECK(this_.GetArena() == nullptr);
  this_._impl_.uid_.Destroy();
  this_._impl_.token_.Destroy();
  this_._impl_.~Impl_();
}

inline void* UserLoginResponse::PlacementNew_(const void*, void* mem,
                                        ::google::protobuf::Arena* arena) {
  return ::new (mem) UserLoginResponse(arena);
}
constexpr auto UserLoginResponse::InternalNewImpl_() {
  return ::google::protobuf::internal::MessageCreator::CopyInit(sizeof(UserLoginResponse),
                                            alignof(UserLoginResponse));
}
PROTOBUF_CONSTINIT
PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::google::protobuf::internal::ClassDataFull UserLoginResponse::_class_data_ = {
    ::google::protobuf::internal::ClassData{
        &_UserLoginResponse_default_instance_._instance,
        &_table_.header,
        nullptr,  // OnDemandRegisterArenaDtor
        nullptr,  // IsInitialized
        &UserLoginResponse::MergeImpl,
        ::google::protobuf::Message::GetNewImpl<UserLoginResponse>(),
#if defined(PROTOBUF_CUSTOM_VTABLE)
        &UserLoginResponse::SharedDtor,
        ::google::protobuf::Message::GetClearImpl<UserLoginResponse>(), &UserLoginResponse::ByteSizeLong,
            &UserLoginResponse::_InternalSerialize,
#endif  // PROTOBUF_CUSTOM_VTABLE
        PROTOBUF_FIELD_OFFSET(UserLoginResponse, _impl_._cached_size_),
        false,
    },
    &UserLoginResponse::kDescriptorMethods,
    &descriptor_table_my_5fgrpc_2eproto,
    nullptr,  // tracker
};
const ::google::protobuf::internal::ClassData* UserLoginResponse::GetClassData() const {
  ::google::protobuf::internal::PrefetchToLocalCache(&_class_data_);
  ::google::protobuf::internal::PrefetchToLocalCache(_class_data_.tc_table);
  return _class_data_.base();
}
PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::_pbi::TcParseTable<2, 3, 0, 42, 2> UserLoginResponse::_table_ = {
  {
    0,  // no _has_bits_
    0, // no _extensions_
    3, 24,  // max_field_number, fast_idx_mask
    offsetof(decltype(_table_), field_lookup_table),
    4294967288,  // skipmap
    offsetof(decltype(_table_), field_entries),
    3,  // num_field_entries
    0,  // num_aux_entries
    offsetof(decltype(_table_), field_names),  // no aux_entries
    _class_data_.base(),
    nullptr,  // post_loop_handler
    ::_pbi::TcParser::GenericFallback,  // fallback
    #ifdef PROTOBUF_PREFETCH_PARSE_TABLE
    ::_pbi::TcParser::GetTable<::my_grpc::UserLoginResponse>(),  // to_prefetch
    #endif  // PROTOBUF_PREFETCH_PARSE_TABLE
  }, {{
    {::_pbi::TcParser::MiniParse, {}},
    // int32 error = 1;
    {::_pbi::TcParser::SingularVarintNoZag1<::uint32_t, offsetof(UserLoginResponse, _impl_.error_), 63>(),
     {8, 63, 0, PROTOBUF_FIELD_OFFSET(UserLoginResponse, _impl_.error_)}},
    // string uid = 2;
    {::_pbi::TcParser::FastUS1,
     {18, 63, 0, PROTOBUF_FIELD_OFFSET(UserLoginResponse, _impl_.uid_)}},
    // string token = 3;
    {::_pbi::TcParser::FastUS1,
     {26, 63, 0, PROTOBUF_FIELD_OFFSET(UserLoginResponse, _impl_.token_)}},
  }}, {{
    65535, 65535
  }}, {{
    // int32 error = 1;
    {PROTOBUF_FIELD_OFFSET(UserLoginResponse, _impl_.error_), 0, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kInt32)},
    // string uid = 2;
    {PROTOBUF_FIELD_OFFSET(UserLoginResponse, _impl_.uid_), 0, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kUtf8String | ::_fl::kRepAString)},
    // string token = 3;
    {PROTOBUF_FIELD_OFFSET(UserLoginResponse, _impl_.token_), 0, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kUtf8String | ::_fl::kRepAString)},
  }},
  // no aux_entries
  {{
    "\31\0\3\5\0\0\0\0"
    "my_grpc.UserLoginResponse"
    "uid"
    "token"
  }},
};

PROTOBUF_NOINLINE void UserLoginResponse::Clear() {
// @@protoc_insertion_point(message_clear_start:my_grpc.UserLoginResponse)
  ::google::protobuf::internal::TSanWrite(&_impl_);
  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  _impl_.uid_.ClearToEmpty();
  _impl_.token_.ClearToEmpty();
  _impl_.error_ = 0;
  _internal_metadata_.Clear<::google::protobuf::UnknownFieldSet>();
}

#if defined(PROTOBUF_CUSTOM_VTABLE)
        ::uint8_t* UserLoginResponse::_InternalSerialize(
            const MessageLite& base, ::uint8_t* target,
            ::google::protobuf::io::EpsCopyOutputStream* stream) {
          const UserLoginResponse& this_ = static_cast<const UserLoginResponse&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
        ::uint8_t* UserLoginResponse::_InternalSerialize(
            ::uint8_t* target,
            ::google::protobuf::io::EpsCopyOutputStream* stream) const {
          const UserLoginResponse& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
          // @@protoc_insertion_point(serialize_to_array_start:my_grpc.UserLoginResponse)
          ::uint32_t cached_has_bits = 0;
          (void)cached_has_bits;

          // int32 error = 1;
          if (this_._internal_error() != 0) {
            target = ::google::protobuf::internal::WireFormatLite::
                WriteInt32ToArrayWithField<1>(
                    stream, this_._internal_error(), target);
          }

          // string uid = 2;
          if (!this_._internal_uid().empty()) {
            const std::string& _s = this_._internal_uid();
            ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
                _s.data(), static_cast<int>(_s.length()), ::google::protobuf::internal::WireFormatLite::SERIALIZE, "my_grpc.UserLoginResponse.uid");
            target = stream->WriteStringMaybeAliased(2, _s, target);
          }

          // string token = 3;
          if (!this_._internal_token().empty()) {
            const std::string& _s = this_._internal_token();
            ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
                _s.data(), static_cast<int>(_s.length()), ::google::protobuf::internal::WireFormatLite::SERIALIZE, "my_grpc.UserLoginResponse.token");
            target = stream->WriteStringMaybeAliased(3, _s, target);
          }

          if (PROTOBUF_PREDICT_FALSE(this_._internal_metadata_.have_unknown_fields())) {
            target =
                ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
                    this_._internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance), target, stream);
          }
          // @@protoc_insertion_point(serialize_to_array_end:my_grpc.UserLoginResponse)
          return target;
        }

#if defined(PROTOBUF_CUSTOM_VTABLE)
        ::size_t UserLoginResponse::ByteSizeLong(const MessageLite& base) {
          const UserLoginResponse& this_ = static_cast<const UserLoginResponse&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
        ::size_t UserLoginResponse::ByteSizeLong() const {
          const UserLoginResponse& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
          // @@protoc_insertion_point(message_byte_size_start:my_grpc.UserLoginResponse)
          ::size_t total_size = 0;

          ::uint32_t cached_has_bits = 0;
          // Prevent compiler warnings about cached_has_bits being unused
          (void)cached_has_bits;

          ::_pbi::Prefetch5LinesFrom7Lines(&this_);
           {
            // string uid = 2;
            if (!this_._internal_uid().empty()) {
              total_size += 1 + ::google::protobuf::internal::WireFormatLite::StringSize(
                                              this_._internal_uid());
            }
            // string token = 3;
            if (!this_._internal_token().empty()) {
              total_size += 1 + ::google::protobuf::internal::WireFormatLite::StringSize(
                                              this_._internal_token());
            }
            // int32 error = 1;
            if (this_._internal_error() != 0) {
              total_size += ::_pbi::WireFormatLite::Int32SizePlusOne(
                  this_._internal_error());
            }
          }
          return this_.MaybeComputeUnknownFieldsSize(total_size,
                                                     &this_._impl_._cached_size_);
        }

void UserLoginResponse::MergeImpl(::google::protobuf::MessageLite& to_msg, const ::google::protobuf::MessageLite& from_msg) {
  auto* const _this = static_cast<UserLoginResponse*>(&to_msg);
  auto& from = static_cast<const UserLoginResponse&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:my_grpc.UserLoginResponse)
  ABSL_DCHECK_NE(&from, _this);
  ::uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  if (!from._internal_uid().empty()) {
    _this->_internal_set_uid(from._internal_uid());
  }
  if (!from._internal_token().empty()) {
    _this->_internal_set_token(from._internal_token());
  }
  if (from._internal_error() != 0) {
    _this->_impl_.error_ = from._impl_.error_;
  }
  _this->_internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(from._internal_metadata_);
}

void UserLoginResponse::CopyFrom(const UserLoginResponse& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:my_grpc.UserLoginResponse)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}


void UserLoginResponse::InternalSwap(UserLoginResponse* PROTOBUF_RESTRICT other) {
  using std::swap;
  auto* arena = GetArena();
  ABSL_DCHECK_EQ(arena, other->GetArena());
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  ::_pbi::ArenaStringPtr::InternalSwap(&_impl_.uid_, &other->_impl_.uid_, arena);
  ::_pbi::ArenaStringPtr::InternalSwap(&_impl_.token_, &other->_impl_.token_, arena);
        swap(_impl_.error_, other->_impl_.error_);
}

::google::protobuf::Metadata UserLoginResponse::GetMetadata() const {
  return ::google::protobuf::Message::GetMetadataImpl(GetClassData()->full());
}
// @@protoc_insertion_point(namespace_scope)
}  // namespace my_grpc
namespace google {
namespace protobuf {
}  // namespace protobuf
}  // namespace google
// @@protoc_insertion_point(global_scope)
PROTOBUF_ATTRIBUTE_INIT_PRIORITY2 static ::std::false_type
    _static_init2_ PROTOBUF_UNUSED =
        (::_pbi::AddDescriptors(&descriptor_table_my_5fgrpc_2eproto),
         ::std::false_type{});
#include "google/protobuf/port_undef.inc"
