// Generated by the gRPC C++ plugin.
// If you make any local change, they will be lost.
// source: my_message.proto

#include "my_message.pb.h"
#include "my_message.grpc.pb.h"

#include <functional>
#include <grpcpp/support/async_stream.h>
#include <grpcpp/support/async_unary_call.h>
#include <grpcpp/impl/channel_interface.h>
#include <grpcpp/impl/client_unary_call.h>
#include <grpcpp/support/client_callback.h>
#include <grpcpp/support/message_allocator.h>
#include <grpcpp/support/method_handler.h>
#include <grpcpp/impl/rpc_service_method.h>
#include <grpcpp/support/server_callback.h>
#include <grpcpp/impl/server_callback_handlers.h>
#include <grpcpp/server_context.h>
#include <grpcpp/impl/service_type.h>
#include <grpcpp/support/sync_stream.h>
namespace my_message {

static const char* VerifyService_method_names[] = {
  "/my_message.VerifyService/get_verify_code",
};

std::unique_ptr< VerifyService::Stub> VerifyService::NewStub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options) {
  (void)options;
  std::unique_ptr< VerifyService::Stub> stub(new VerifyService::Stub(channel, options));
  return stub;
}

VerifyService::Stub::Stub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options)
  : channel_(channel), rpcmethod_get_verify_code_(VerifyService_method_names[0], options.suffix_for_stats(),::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  {}

::grpc::Status VerifyService::Stub::get_verify_code(::grpc::ClientContext* context, const ::my_message::GetVerifyRequest& request, ::my_message::GetVerifyResponse* response) {
  return ::grpc::internal::BlockingUnaryCall< ::my_message::GetVerifyRequest, ::my_message::GetVerifyResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_get_verify_code_, context, request, response);
}

void VerifyService::Stub::async::get_verify_code(::grpc::ClientContext* context, const ::my_message::GetVerifyRequest* request, ::my_message::GetVerifyResponse* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::my_message::GetVerifyRequest, ::my_message::GetVerifyResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_get_verify_code_, context, request, response, std::move(f));
}

void VerifyService::Stub::async::get_verify_code(::grpc::ClientContext* context, const ::my_message::GetVerifyRequest* request, ::my_message::GetVerifyResponse* response, ::grpc::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_get_verify_code_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::my_message::GetVerifyResponse>* VerifyService::Stub::PrepareAsyncget_verify_codeRaw(::grpc::ClientContext* context, const ::my_message::GetVerifyRequest& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::my_message::GetVerifyResponse, ::my_message::GetVerifyRequest, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_get_verify_code_, context, request);
}

::grpc::ClientAsyncResponseReader< ::my_message::GetVerifyResponse>* VerifyService::Stub::Asyncget_verify_codeRaw(::grpc::ClientContext* context, const ::my_message::GetVerifyRequest& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsyncget_verify_codeRaw(context, request, cq);
  result->StartCall();
  return result;
}

VerifyService::Service::Service() {
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      VerifyService_method_names[0],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< VerifyService::Service, ::my_message::GetVerifyRequest, ::my_message::GetVerifyResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](VerifyService::Service* service,
             ::grpc::ServerContext* ctx,
             const ::my_message::GetVerifyRequest* req,
             ::my_message::GetVerifyResponse* resp) {
               return service->get_verify_code(ctx, req, resp);
             }, this)));
}

VerifyService::Service::~Service() {
}

::grpc::Status VerifyService::Service::get_verify_code(::grpc::ServerContext* context, const ::my_message::GetVerifyRequest* request, ::my_message::GetVerifyResponse* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}


}  // namespace my_message

